# Generated by Django 5.1.3 on 2024-12-05 18:41

import django.db.models.deletion
import validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cupom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                (
                    "porcentagem",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Editora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=9)),
                ("uf", models.CharField(max_length=2)),
                ("cidade", models.CharField(max_length=30)),
                ("bairro", models.CharField(max_length=50)),
                ("rua", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("complemento", models.CharField(blank=True, max_length=30, null=True)),
                ("identificacao", models.CharField(default="Endereço", max_length=30)),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneroLiterario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rg", models.CharField(max_length=9)),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=5
                    ),
                ),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente_do_carrinho",
                        to="elibrosLoja.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("subtitulo", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "data_de_publicacao",
                    models.DateField(
                        blank=True, null=True, validators=[validators.nao_e_no_futuro]
                    ),
                ),
                (
                    "ano_de_publicacao",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            validators.nao_negativo,
                            validators.nao_nulo,
                            validators.nao_e_no_futuro,
                        ],
                    ),
                ),
                ("capa", models.ImageField(blank=True, null=True, upload_to="capas/")),
                ("ISBN", models.CharField(max_length=15, unique=True)),
                ("sinopse", models.TextField(blank=True, null=True)),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[validators.nao_negativo, validators.nao_nulo],
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(validators=[validators.nao_negativo]),
                ),
                (
                    "qtd_vendidos",
                    models.IntegerField(
                        default=0,
                        validators=[validators.nao_negativo],
                        verbose_name="Vendidos",
                    ),
                ),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ManyToManyField(
                        blank=True,
                        related_name="Autor_do_Livro",
                        to="elibrosLoja.autor",
                    ),
                ),
                (
                    "categoria",
                    models.ManyToManyField(
                        blank=True,
                        related_name="Categoria_do_Livro",
                        to="elibrosLoja.categoria",
                    ),
                ),
                (
                    "editora",
                    models.ManyToManyField(
                        blank=True,
                        related_name="Editora_do_Livro",
                        to="elibrosLoja.editora",
                    ),
                ),
                (
                    "genero_literario",
                    models.ManyToManyField(
                        blank=True,
                        related_name="Genero_Literario_do_Livro",
                        to="elibrosLoja.generoliterario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCarrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "preco",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "carrinho",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_do_carrinho",
                        to="elibrosLoja.carrinho",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livro_selecionado",
                        to="elibrosLoja.livro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "numero_pedido",
                    models.CharField(
                        default="072576449544",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="nao_confirmado/processando",
                        max_length=50,
                        validators=[validators.nao_nulo],
                    ),
                ),
                ("data_de_pedido", models.DateTimeField()),
                ("entrega_estimada", models.DateTimeField()),
                ("data_de_entrega", models.DateTimeField(blank=True, null=True)),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[validators.nao_negativo, validators.nao_nulo],
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        validators=[validators.nao_negativo],
                    ),
                ),
                (
                    "quantia_itens",
                    models.IntegerField(
                        default=0, validators=[validators.nao_negativo]
                    ),
                ),
                (
                    "qtd_vendidos",
                    models.IntegerField(
                        default=0,
                        validators=[validators.nao_negativo],
                        verbose_name="Vendidos",
                    ),
                ),
                ("data_de_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_de_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente_do_pedido",
                        to="elibrosLoja.cliente",
                    ),
                ),
                (
                    "itens",
                    models.ManyToManyField(
                        related_name="itens_do_pedido", to="elibrosLoja.itemcarrinho"
                    ),
                ),
            ],
        ),
    ]
