# Generated by Django 5.1.3 on 2024-12-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0002_alter_pedido_numero_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="305356228933", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
