# Generated by Django 5.1.3 on 2024-12-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0005_remove_cupom_porcentagem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="editora",
        ),
        migrations.AlterModelOptions(
            name="administrador",
            options={
                "verbose_name": "Administrador",
                "verbose_name_plural": "Administradores",
            },
        ),
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="cupom",
            options={"verbose_name": "Cupom", "verbose_name_plural": "Cupons"},
        ),
        migrations.AlterModelOptions(
            name="endereco",
            options={"verbose_name": "Endereço", "verbose_name_plural": "Endereços"},
        ),
        migrations.AlterModelOptions(
            name="generoliterario",
            options={
                "verbose_name": "Gênero Literário",
                "verbose_name_plural": "Gêneros Literários",
            },
        ),
        migrations.AlterModelOptions(
            name="itemcarrinho",
            options={
                "verbose_name": "Item de carrinho",
                "verbose_name_plural": "Itens de carrinho",
            },
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="285369477084", max_length=12, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="Editora",
        ),
        migrations.AddField(
            model_name="livro",
            name="editora",
            field=models.CharField(default="Editora não informada", max_length=100),
        ),
    ]
