# Generated by Django 5.1.3 on 2024-12-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "elibrosLoja",
            "0006_remove_livro_editora_alter_administrador_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="381070577699", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
