# Generated by Django 5.1.3 on 2024-12-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0011_alter_categoria_atualizado_por_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="713777859568", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="713777859568", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
