# Generated by Django 5.1.3 on 2024-12-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0013_alter_historicalpedido_numero_pedido_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="autor",
            name="data_de_atualizacao",
        ),
        migrations.RemoveField(
            model_name="autor",
            name="data_de_cadastro",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="cupom",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="generoliterario",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="historicalautor",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="historicalautor",
            name="data_de_atualizacao",
        ),
        migrations.RemoveField(
            model_name="historicalautor",
            name="data_de_cadastro",
        ),
        migrations.RemoveField(
            model_name="historicalcategoria",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="historicalcliente",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="historicalcupom",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="historicalgeneroliterario",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="historicallivro",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="historicallivro",
            name="data_de_atualizacao",
        ),
        migrations.RemoveField(
            model_name="historicallivro",
            name="data_de_cadastro",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="data_de_atualizacao",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="data_de_cadastro",
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="114186697162", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="114186697162", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
