# Generated by Django 5.1.3 on 2024-12-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0015_categoria_atualizado_por_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="historicalcategoria",
            name="atualizado_por",
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="671819881950", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="671819881950", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
