# Generated by Django 5.1.3 on 2024-12-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0017_remove_carrinho_data_de_atualizacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="identificacao",
            field=models.CharField(
                blank=True, default="Endereço", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalendereco",
            name="identificacao",
            field=models.CharField(
                blank=True, default="Endereço", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="056586127865", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="056586127865", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
