# Generated by Django 5.1.3 on 2024-12-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0019_remove_endereco_criado_por_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpedido",
            name="qtd_vendidos",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="qtd_vendidos",
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="650787520486", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="650787520486", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
