# Generated by Django 5.1.3 on 2025-01-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0021_alter_historicallivro_ano_de_publicacao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor(es)"},
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="historicalautor",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Autor(es)",
                "verbose_name_plural": "historical Autor(es)s",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcategoria",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Categoria",
                "verbose_name_plural": "historical Categorias",
            },
        ),
        migrations.AlterField(
            model_name="historicallivro",
            name="capa",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Capa"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="979836351509", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="capa",
            field=models.ImageField(
                blank=True, null=True, upload_to="capas/", verbose_name="Capa"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="979836351509", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
