# Generated by Django 5.1.3 on 2025-01-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0023_alter_historicalpedido_numero_pedido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="352067858432", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="352067858432", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
