# Generated by Django 5.1.5 on 2025-01-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0024_alter_historicalpedido_numero_pedido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpedido",
            name="data_de_cancelamento",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="data_de_cancelamento",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="741677142548", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="741677142548", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
