# Generated by Django 5.1.5 on 2025-01-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0026_estado_autor_cidade_historicalautor_cidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="historicalautor",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="autor",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="historicalautor",
            name="cidade",
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="957612472769", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="957612472769", max_length=12, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="Estado",
        ),
    ]
