# Generated by Django 5.1.5 on 2025-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "elibrosLoja",
            "0027_remove_autor_estado_remove_historicalautor_estado_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GeneroLiterario",
            new_name="Genero",
        ),
        migrations.RenameModel(
            old_name="HistoricalGeneroLiterario",
            new_name="HistoricalGenero",
        ),
        migrations.AlterModelOptions(
            name="genero",
            options={"verbose_name": "Gênero", "verbose_name_plural": "Gêneros"},
        ),
        migrations.AlterModelOptions(
            name="historicalgenero",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Gênero",
                "verbose_name_plural": "historical Gêneros",
            },
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="877896706073", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="877896706073", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
