# Generated by Django 5.1.5 on 2025-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0028_rename_generoliterario_genero_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="genero_literario",
            new_name="genero",
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="875112250589", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="875112250589", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
