# Generated by Django 5.2.4 on 2025-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0029_rename_genero_literario_livro_genero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="434627221912", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="434627221912", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
