# Generated by Django 5.2.4 on 2025-07-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0031_alter_historicalpedido_numero_pedido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="241716736741", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="241716736741", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
