# Generated by Django 5.2.4 on 2025-07-26 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0035_alter_historicalpedido_numero_pedido_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="362475290869", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="362475290869", max_length=12, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.TextField(
                        help_text="Comentário sobre o livro (máximo 1000 caracteres)",
                        max_length=1000,
                        verbose_name="Texto da Avaliação",
                    ),
                ),
                (
                    "curtidas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de curtidas que esta avaliação recebeu",
                        verbose_name="Curtidas",
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="elibrosLoja.livro",
                        verbose_name="Livro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-data_publicacao"],
            },
        ),
        migrations.CreateModel(
            name="CurtidaAvaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_curtida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Curtida"
                    ),
                ),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curtidas_usuarios",
                        to="elibrosLoja.avaliacao",
                        verbose_name="Avaliação",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curtidas_avaliacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curtida de Avaliação",
                "verbose_name_plural": "Curtidas de Avaliações",
            },
        ),
        migrations.AddIndex(
            model_name="avaliacao",
            index=models.Index(
                fields=["livro", "-data_publicacao"],
                name="elibrosLoja_livro_i_10ae49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="avaliacao",
            index=models.Index(
                fields=["usuario", "-data_publicacao"],
                name="elibrosLoja_usuario_b4e713_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="avaliacao",
            unique_together={("usuario", "livro")},
        ),
        migrations.AlterUniqueTogether(
            name="curtidaavaliacao",
            unique_together={("usuario", "avaliacao")},
        ),
    ]
