# Generated by Django 5.2.4 on 2025-07-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0038_alter_historicalpedido_numero_pedido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="516226124129", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="516226124129", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
