# Generated by Django 5.2.6 on 2025-09-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0041_alter_historicalpedido_numero_pedido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="452988343750", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="452988343750", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
