# Generated by Django 5.2.7 on 2025-10-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0042_alter_historicalpedido_numero_pedido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="367824215732", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="367824215732", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
