# Generated by Django 5.2.7 on 2025-10-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0043_alter_historicalpedido_numero_pedido_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallivro",
            name="capa",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="capa",
        ),
        migrations.AddField(
            model_name="historicallivro",
            name="capa_file_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ImageKit File ID"
            ),
        ),
        migrations.AddField(
            model_name="historicallivro",
            name="capa_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL da Capa"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="capa_file_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ImageKit File ID"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="capa_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL da Capa"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpedido",
            name="numero_pedido",
            field=models.CharField(
                db_index=True, default="179513825525", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="179513825525", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
