# Generated by Django 5.1.3 on 2024-12-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="conta_ativa",
        ),
    ]
