# Generated by Django 5.1.3 on 2024-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_usuario_conta_ativa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="outro_genero",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="CPF",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "Feminino"),
                    ("M", "Masculino"),
                    ("NB", "Não-binário"),
                    ("PND", "Prefiro não dizer"),
                ],
                default="F",
                max_length=20,
                null=True,
                verbose_name="Identidade de gênero",
            ),
        ),
    ]
