# Generated by Django 5.1.3 on 2024-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_usuario_managers_alter_usuario_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="genero",
            field=models.CharField(
                choices=[
                    ("F", "Feminino"),
                    ("M", "Masculino"),
                    ("NB", "Não-binário"),
                    ("PND", "Prefiro não dizer"),
                    ("NI", "Não informado"),
                ],
                default="NI",
                max_length=20,
                verbose_name="Identidade de gênero",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(default="Nome não informado", max_length=100),
        ),
    ]
