# Generated by Django 5.1.3 on 2025-01-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_usuario_genero_alter_usuario_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="email_is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="dt_nasc",
            field=models.DateField(
                default="2000-01-01", null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="genero",
            field=models.CharField(
                choices=[
                    ("F", "Feminino"),
                    ("M", "Masculino"),
                    ("NB", "Não-binário"),
                    ("PND", "Prefiro não dizer"),
                    ("NI", "Não informado"),
                ],
                default="NI",
                max_length=20,
                null=True,
                verbose_name="Identidade de gênero",
            ),
        ),
    ]
