# Generated by Django 5.2.4 on 2025-07-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_usuario_email_is_verified_alter_usuario_dt_nasc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="login_token",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
