# Generated by Django 5.2.7 on 2025-10-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_usuario_login_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="foto_de_perfil",
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto_de_perfil_file_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ImageKit File ID"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto_de_perfil_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="URL da Foto de Perfil",
            ),
        ),
    ]
