from .test_administrador import AdministradorTestCase
from .test_autor import AutorTestCase
from .test_avaliacao import AvaliacaoTestCase
from .test_carrinho import CarrinhoTestCase
from .test_categoria import CategoriaTestCase
from .test_cliente import ClienteTestCase
from .test_cupom import CupomTestCase
from .test_endereco import EnderecoTestCase
from .test_genero import GeneroTestCase
from .test_itemcarrinho import ItemCarrinhoTestCase
from .test_livro import LivroTestCase
from .test_pedido import PedidoTestCase